/* ===========================
   DATA PRINCIPAL (MATRIZ MINERA)
   =========================== */

const MATRIZ_MINERA = [
  // ===== Perforista =====
  {
    puestoId: "perforista",
    puestoNombre: "Perforista",
    actividadId: "operar-perforadora",
    actividadNombre: "Operar perforadora",
    epp: "Respirador cara completa P100/PAPR, casco clase E con lámpara, goggles herméticos, doble protección auditiva, guantes antivibración, botas metatarsales, ropa FR",
    riesgo: "Silicosis",
    impacto: 5,
    color: "rojo",
  },
  {
    puestoId: "perforista",
    puestoNombre: "Perforista",
    actividadId: "cambiar-barrenas",
    actividadNombre: "Cambiar barrenas",
    epp: "Guantes anticorte nivel alto, mangas Kevlar, lentes de impacto, casco con barbiquejo, botas reforzadas",
    riesgo: "Amputación",
    impacto: 4,
    color: "naranja",
  },
  {
    puestoId: "perforista",
    puestoNombre: "Perforista",
    actividadId: "verificar-frente",
    actividadNombre: "Verificar estabilidad del frente",
    epp: "Detector multigas, autorrescatador, casco, lámpara minera, botas de alta tracción",
    riesgo: "Derrumbe",
    impacto: 5,
    color: "rojo",
  },
  {
    puestoId: "perforista",
    puestoNombre: "Perforista",
    actividadId: "lubricar-equipo",
    actividadNombre: "Lubricar equipo",
    epp: "Guantes contra hidrocarburos, mandil impermeable, lentes, botas antiderrapantes",
    riesgo: "Contacto químico",
    impacto: 3,
    color: "amarillo",
  },
  {
    puestoId: "perforista",
    puestoNombre: "Perforista",
    actividadId: "herramientas-pesadas",
    actividadNombre: "Manipular herramientas pesadas",
    epp: "Guantes de alto impacto, faja ergonómica, botas con casquillo",
    riesgo: "Lesión lumbar",
    impacto: 3,
    color: "amarillo",
  },
  {
    puestoId: "perforista",
    puestoNombre: "Perforista",
    actividadId: "ruido-extremo",
    actividadNombre: "Trabajar con ruido extremo",
    epp: "Tapones + orejeras NRR alto, casco",
    riesgo: "Pérdida auditiva",
    impacto: 4,
    color: "naranja",
  },
  {
    puestoId: "perforista",
    puestoNombre: "Perforista",
    actividadId: "polvo-silice",
    actividadNombre: "Perforar en polvo de sílice",
    epp: "Respirador motorizado, overol desechable, capucha, goggles sellados",
    riesgo: "Enfermedad pulmonar",
    impacto: 5,
    color: "rojo",
  },
  {
    puestoId: "perforista",
    puestoNombre: "Perforista",
    actividadId: "evacuacion",
    actividadNombre: "Evacuación de emergencia",
    epp: "Autorrescatador de oxígeno, casco, lámpara, radio intrínseco",
    riesgo: "Asfixia",
    impacto: 5,
    color: "rojo",
  },

  // ===== Operador de Jumbo =====
  {
    puestoId: "operador-jumbo",
    puestoNombre: "Operador de Jumbo",
    actividadId: "perforar-tunel",
    actividadNombre: "Perforar túnel",
    epp: "Casco con barbiquejo, respirador P100, guantes antivibración, botas reforzadas",
    riesgo: "Derrumbe",
    impacto: 5,
    color: "rojo",
  },
  {
    puestoId: "operador-jumbo",
    puestoNombre: "Operador de Jumbo",
    actividadId: "sistema-hidraulico",
    actividadNombre: "Controlar sistema hidráulico",
    epp: "Guantes mecánicos, lentes alto impacto, casco",
    riesgo: "Atrapamiento",
    impacto: 4,
    color: "naranja",
  },
  {
    puestoId: "operador-jumbo",
    puestoNombre: "Operador de Jumbo",
    actividadId: "revisar-mangueras",
    actividadNombre: "Revisar mangueras",
    epp: "Careta facial, guantes resistentes a presión, lentes",
    riesgo: "Latigazo hidráulico",
    impacto: 4,
    color: "naranja",
  },
  {
    puestoId: "operador-jumbo",
    puestoNombre: "Operador de Jumbo",
    actividadId: "espacios-confinados",
    actividadNombre: "Trabajar en espacios confinados",
    epp: "Monitor multigas, SCBA, arnés de rescate",
    riesgo: "Falta de oxígeno",
    impacto: 5,
    color: "rojo",
  },
  {
    puestoId: "operador-jumbo",
    puestoNombre: "Operador de Jumbo",
    actividadId: "posicionar-equipo",
    actividadNombre: "Posicionar equipo",
    epp: "Chaleco alta visibilidad clase 3, casco, botas",
    riesgo: "Colisión",
    impacto: 4,
    color: "naranja",
  },
  {
    puestoId: "operador-jumbo",
    puestoNombre: "Operador de Jumbo",
    actividadId: "mantenimiento-basico",
    actividadNombre: "Mantenimiento básico",
    epp: "Guantes mecánicos, lentes, casco",
    riesgo: "Golpes",
    impacto: 2,
    color: "verde",
  },
  {
    puestoId: "operador-jumbo",
    puestoNombre: "Operador de Jumbo",
    actividadId: "baja-iluminacion",
    actividadNombre: "Operar con baja iluminación",
    epp: "Casco con lámpara LED, ropa reflejante",
    riesgo: "Accidentes",
    impacto: 3,
    color: "amarillo",
  },
  {
    puestoId: "operador-jumbo",
    puestoNombre: "Operador de Jumbo",
    actividadId: "vibraciones",
    actividadNombre: "Exposición a vibraciones",
    epp: "Guantes antivibración, asiento ergonómico",
    riesgo: "Daño musculoesquelético",
    impacto: 3,
    color: "amarillo",
  },

  // ===== Técnico de ventilación =====
  {
    puestoId: "tecnico-ventilacion",
    puestoNombre: "Técnico de ventilación",
    actividadId: "medir-oxigeno",
    actividadNombre: "Medir oxígeno",
    epp: "Detector multigas, respirador media cara, casco",
    riesgo: "Hipoxia",
    impacto: 5,
    color: "rojo",
  },
  {
    puestoId: "tecnico-ventilacion",
    puestoNombre: "Técnico de ventilación",
    actividadId: "gases-toxicos",
    actividadNombre: "Detectar gases tóxicos",
    epp: "Respirador cara completa, ropa FR, lentes",
    riesgo: "Intoxicación",
    impacto: 5,
    color: "rojo",
  },
  {
    puestoId: "tecnico-ventilacion",
    puestoNombre: "Técnico de ventilación",
    actividadId: "instalar-ductos",
    actividadNombre: "Instalar ductos",
    epp: "Arnés, casco, guantes mecánicos, botas",
    riesgo: "Caídas",
    impacto: 4,
    color: "naranja",
  },
  {
    puestoId: "tecnico-ventilacion",
    puestoNombre: "Técnico de ventilación",
    actividadId: "zonas-toxicas",
    actividadNombre: "Ingresar a zonas tóxicas",
    epp: "SCBA, traje encapsulado, guantes químicos",
    riesgo: "Muerte",
    impacto: 5,
    color: "rojo",
  },
  {
    puestoId: "tecnico-ventilacion",
    puestoNombre: "Técnico de ventilación",
    actividadId: "revisar-ventiladores",
    actividadNombre: "Revisar ventiladores",
    epp: "Protección auditiva, lentes, guantes",
    riesgo: "Ruido",
    impacto: 3,
    color: "amarillo",
  },
  {
    puestoId: "tecnico-ventilacion",
    puestoNombre: "Técnico de ventilación",
    actividadId: "temperaturas-extremas",
    actividadNombre: "Temperaturas extremas",
    epp: "Chaleco de enfriamiento o ropa térmica",
    riesgo: "Estrés térmico",
    impacto: 3,
    color: "amarillo",
  },
  {
    puestoId: "tecnico-ventilacion",
    puestoNombre: "Técnico de ventilación",
    actividadId: "ajustar-flujo",
    actividadNombre: "Ajustar flujo de aire",
    epp: "Casco, guantes, botas",
    riesgo: "Golpes",
    impacto: 2,
    color: "verde",
  },
  {
    puestoId: "tecnico-ventilacion",
    puestoNombre: "Técnico de ventilación",
    actividadId: "inspeccionar-rutas",
    actividadNombre: "Inspeccionar rutas",
    epp: "Casco, lámpara minera, botas",
    riesgo: "Derrumbe",
    impacto: 4,
    color: "naranja",
  },

  // ===== Electricista minero =====
  {
    puestoId: "electricista-minero",
    puestoNombre: "Electricista minero",
    actividadId: "reparar-tableros",
    actividadNombre: "Reparar tableros",
    epp: "Traje contra arco eléctrico, pantalla facial, balaclava ignífuga, guantes dieléctricos",
    riesgo: "Arco eléctrico",
    impacto: 5,
    color: "rojo",
  },
  {
    puestoId: "electricista-minero",
    puestoNombre: "Electricista minero",
    actividadId: "instalar-cableado",
    actividadNombre: "Instalar cableado",
    epp: "Casco dieléctrico, botas dieléctricas, lentes, herramientas aisladas",
    riesgo: "Electrocución",
    impacto: 5,
    color: "rojo",
  },
  {
    puestoId: "electricista-minero",
    puestoNombre: "Electricista minero",
    actividadId: "probar-voltaje",
    actividadNombre: "Probar voltaje",
    epp: "Guantes aislantes, lentes, detector de voltaje",
    riesgo: "Quemaduras",
    impacto: 4,
    color: "naranja",
  },
  {
    puestoId: "electricista-minero",
    puestoNombre: "Electricista minero",
    actividadId: "loto",
    actividadNombre: "Aplicar LOTO",
    epp: "Guantes dieléctricos, casco",
    riesgo: "Energización inesperada",
    impacto: 5,
    color: "rojo",
  },
  {
    puestoId: "electricista-minero",
    puestoNombre: "Electricista minero",
    actividadId: "humedad",
    actividadNombre: "Trabajar en humedad",
    epp: "Botas dieléctricas, tapete aislante",
    riesgo: "Descarga eléctrica",
    impacto: 5,
    color: "rojo",
  },
  {
    puestoId: "electricista-minero",
    puestoNombre: "Electricista minero",
    actividadId: "atender-fallas",
    actividadNombre: "Atender fallas",
    epp: "Ropa FR, pantalla facial",
    riesgo: "Explosión",
    impacto: 5,
    color: "rojo",
  },
  {
    puestoId: "electricista-minero",
    puestoNombre: "Electricista minero",
    actividadId: "energia-residual",
    actividadNombre: "Detectar energía residual",
    epp: "Detector de voltaje, guantes",
    riesgo: "Choque eléctrico",
    impacto: 4,
    color: "naranja",
  },
  {
    puestoId: "electricista-minero",
    puestoNombre: "Electricista minero",
    actividadId: "mantenimiento",
    actividadNombre: "Mantenimiento",
    epp: "Guantes mecánicos, lentes",
    riesgo: "Golpes",
    impacto: 2,
    color: "verde",
  },

  // ===== Operador de camión Off-Road =====
  {
    puestoId: "operador-offroad",
    puestoNombre: "Operador de camión Off-Road",
    actividadId: "conducir-rampas",
    actividadNombre: "Conducir en rampas",
    epp: "Cinturón de seguridad, casco, botas antiderrapantes",
    riesgo: "Volcadura",
    impacto: 5,
    color: "rojo",
  },
  {
    puestoId: "operador-offroad",
    puestoNombre: "Operador de camión Off-Road",
    actividadId: "baja-visibilidad",
    actividadNombre: "Operar con baja visibilidad",
    epp: "Ropa alta visibilidad, lámpara, lentes",
    riesgo: "Colisión",
    impacto: 5,
    color: "rojo",
  },
  {
    puestoId: "operador-offroad",
    puestoNombre: "Operador de camión Off-Road",
    actividadId: "cargar-material",
    actividadNombre: "Cargar material",
    epp: "Casco, lentes de impacto, botas",
    riesgo: "Caída de rocas",
    impacto: 4,
    color: "naranja",
  },
  {
    puestoId: "operador-offroad",
    puestoNombre: "Operador de camión Off-Road",
    actividadId: "revisar-frenos",
    actividadNombre: "Revisar frenos",
    epp: "Guantes mecánicos, lentes",
    riesgo: "Atrapamiento",
    impacto: 4,
    color: "naranja",
  },
  {
    puestoId: "operador-offroad",
    puestoNombre: "Operador de camión Off-Road",
    actividadId: "descargar-material",
    actividadNombre: "Descargar material",
    epp: "Casco con barbiquejo",
    riesgo: "Golpes",
    impacto: 3,
    color: "amarillo",
  },
  {
    puestoId: "operador-offroad",
    puestoNombre: "Operador de camión Off-Road",
    actividadId: "revisar-neumaticos",
    actividadNombre: "Revisar neumáticos",
    epp: "Botas metatarsales, guantes reforzados",
    riesgo: "Sobreesfuerzo",
    impacto: 3,
    color: "amarillo",
  },
  {
    puestoId: "operador-offroad",
    puestoNombre: "Operador de camión Off-Road",
    actividadId: "jornadas",
    actividadNombre: "Jornadas prolongadas",
    epp: "Soporte lumbar, asiento ergonómico",
    riesgo: "Fatiga",
    impacto: 4,
    color: "naranja",
  },
  {
    puestoId: "operador-offroad",
    puestoNombre: "Operador de camión Off-Road",
    actividadId: "cargar-combustible",
    actividadNombre: "Cargar combustible",
    epp: "Guantes químicos, ropa antiestática, lentes",
    riesgo: "Incendio",
    impacto: 5,
    color: "rojo",
  },
];

// Exponer global para HTML
window.MATRIZ_MINERA = MATRIZ_MINERA;
const IMAGEN_POR_PUESTO = {
  // AQUI INSERTA RUTAS DE IMAGENES POR PUESTO
  "perforista": "imagenes/perforacion.jpg",
  "operador-jumbo": "imagenes/jumbo.jpg",
  "tecnico-ventilacion": "imagenes/ventilacion.jpg",
  "electricista-minero": "imagenes/electrico.jpg",
  "operador-offroad": "imagenes/operadorCamion.jpg",
};

// Exponer global
window.IMAGEN_POR_PUESTO = IMAGEN_POR_PUESTO;

const EPP_IMAGENES_POR_ACTIVIDAD = {
  // ===== PERFORISTA =====
  "operar-perforadora": [
    { label: "Casco clase E con lámpara", src: "imagenes/perforista/1/barbiquejo.jpg" },    
    { label: "Respirador (P100 / PAPR)", src: "imagenes/perforista/1/respirador.jpg" },     
    { label: "Guantes antivibración", src: "imagenes/perforista/1/guantes.jpg" },         
    { label: "Botas metatarsales", src: "imagenes/perforista/1/botas.jpg" },             
  ],
  "cambiar-barrenas": [
    { label: "Casco con barbiquejo", src: "imagenes/perforista/2/barbiquejo.jpg" },
    { label: "Lentes de impacto", src: "imagenes/perforista/2/lentes.jpg" },
    { label: "Guantes anticorte (alto nivel)", src: "imagenes/perforista/2/guantes.jpg" },
    { label: "Botas reforzadas", src: "imagenes/perforista/2/botas.jpg" },
  ],
  "verificar-frente": [
    { label: "Casco con lámpara minera", src: "imagenes/perforista/3/casco.jpg" },
    { label: "Detector multigas", src: "imagenes/perforista/3/detector.jpg" },
    { label: "Autorrescatador", src: "imagenes/perforista/3/gas.jpg" },
    { label: "Botas alta tracción", src: "imagenes/perforista/3/botas.jpg" },
  ],
  "lubricar-equipo": [
    { label: "Guantes contra hidrocarburos", src: "imagenes/perforista/4/guantes.jpg" },
    { label: "Lentes de seguridad", src: "imagenes/perforista/4/lentes.jpg" },
    { label: "Mandil impermeable", src: "imagenes/perforista/4/mandil.jpg" },
    { label: "Botas antiderrapantes", src: "imagenes/perforista/4/botas.jpg" },
  ],
  "herramientas-pesadas": [
    { label: "Guantes alto impacto", src: "imagenes/perforista/5/guantes.jpg" },
    { label: "Faja ergonómica", src: "imagenes/perforista/5/faja.jpg" },
    { label: "Botas con casquillo", src: "imagenes/perforista/5/botas.jpg" },
    { label: "Protección adicional", src: "imagenes/perforista/5/lentes.jpg" }, 
  ],
  "ruido-extremo": [
    { label: "Tapones auditivos (NRR alto)", src: "imagenes/perforista/6/tapones.jpg" },
    { label: "Orejeras (NRR alto)", src: "imagenes/perforista/6/orejeras.jpg" },
    { label: "Casco", src: "imagenes/perforista/6/casco.jpg" },
    { label: "Goggles / lentes", src: "imagenes/perforista/6/lentes.jpg" },
  ],
  "polvo-silice": [
    { label: "Respirador motorizado", src: "imagenes/perforista/7/respirador.jpg" },
    { label: "Goggles sellados", src: "imagenes/perforista/7/lentes.jpg" },
    { label: "Overol desechable", src: "imagenes/perforista/7/overol.jpg" },
    { label: "Capucha", src: "imagenes/perforista/7/capucha.jpg" },
  ],
  "evacuacion": [
    { label: "Autorrescatador de oxígeno", src: "imagenes/perforista/8/autorres.jpg" },
    { label: "Casco", src: "imagenes/perforista/8/casco.jpg" },
    { label: "Radio intrínsecamente seguro", src: "imagenes/perforista/8/radio.jpg" },
    { label: "Protección adicional", src: "imagenes/perforista/8/lampara.jpg" },
  ],

  // ===== OPERADOR DE JUMBO =====
  "perforar-tunel": [
    { label: "Casco con barbiquejo", src: "imagenes/jumbo/1/casco.jpg" },
    { label: "Respirador P100", src: "imagenes/jumbo/1/respirador.jpg" },
    { label: "Guantes antivibración", src: "imagenes/jumbo/1/guantes.jpg" },
    { label: "Botas reforzadas", src: "imagenes/jumbo/1/botas.jpg" },
  ],
  "sistema-hidraulico": [
    { label: "Casco", src: "imagenes/jumbo/2/casco.jpg" },
    { label: "Lentes alto impacto", src: "imagenes/jumbo/2/lentes.jpg" },
    { label: "Guantes mecánicos", src: "imagenes/jumbo/2/guantes.jpg" },
    { label: "Botas reforzadas", src: "imagenes/jumbo/2/botas.jpg" },
  ],
  "revisar-mangueras": [
    { label: "Careta facial", src: "imagenes/jumbo/3/careta.jpg" },
    { label: "Lentes", src: "imagenes/jumbo/3/lentes.jpg" },
    { label: "Guantes resistentes a presión", src: "imagenes/jumbo/3/guantes.jpg" },
    { label: "Botas", src: "imagenes/jumbo/3/botas.jpg" },
  ],
  "espacios-confinados": [
    { label: "Monitor multigas", src: "imagenes/jumbo/4/gas.jpg" },
    { label: "SCBA", src: "imagenes/jumbo/4/scba.jpg" },
    { label: "Arnés de rescate", src: "imagenes/jumbo/4/arnes.jpg" },
    { label: "Casco", src: "imagenes/jumbo/4/casco.jpg" },
  ],
  "posicionar-equipo": [
    { label: "Chaleco alta visibilidad (Clase 3)", src: "imagenes/jumbo/5/chaleco.jpg" },
    { label: "Casco", src: "imagenes/jumbo/5/casco.jpg" },
    { label: "Botas", src: "imagenes/jumbo/5/botas.jpg" },
    { label: "Señalización / Conos", src: "imagenes/jumbo/5/cono.jpg" },
  ],
  "mantenimiento-basico": [
    { label: "Guantes mecánicos", src: "imagenes/jumbo/6/guantes.jpg" },
    { label: "Lentes", src: "imagenes/jumbo/6/lentes.jpg" },
    { label: "Casco", src: "imagenes/jumbo/6/casco.jpg" },
    { label: "Botas", src: "imagenes/jumbo/6/botas.jpg" },
  ],
  "baja-iluminacion": [
    { label: "Casco con lámpara LED", src: "imagenes/jumbo/7/casco.jpg" },
    { label: "Ropa reflejante", src: "imagenes/jumbo/7/ropa.jpg" },
    { label: "Botas", src: "imagenes/jumbo/7/bota.jpg" },
    { label: "Lentes", src: "imagenes/jumbo/7/lentes.jpg" },
  ],
  "vibraciones": [
    { label: "Guantes antivibración", src: "imagenes/jumbo/8/guantes.jpg" },
    { label: "Asiento ergonómico", src: "imagenes/jumbo/8/asiento.jpg" },
    { label: "Botas", src: "imagenes/jumbo/8/bota.jpg" },
    { label: "Protección adicional", src: "imagenes/jumbo/8/lumbar.jpg" },
  ],

  // ===== TÉCNICO DE VENTILACIÓN =====
  "medir-oxigeno": [
    { label: "Detector multigas", src: "imagenes/ventilacion/1/gas.jpg" },
    { label: "Casco", src: "imagenes/ventilacion/1/casco.jpg" },
    { label: "Respirador media cara", src: "imagenes/ventilacion/1/respirador.jpg" },
    { label: "Botas", src: "imagenes/ventilacion/1/botas.jpg" },
  ],
  "gases-toxicos": [
    { label: "Respirador cara completa", src: "imagenes/ventilacion/2/respirador.jpg" },
    { label: "Ropa FR", src: "imagenes/ventilacion/2/ropa.jpg" },
    { label: "Lentes", src: "imagenes/ventilacion/2/lentes.jpg" },
    { label: "Guantes", src: "imagenes/ventilacion/2/guantes.jpg" },
  ],
  "instalar-ductos": [
    { label: "Arnés", src: "imagenes/ventilacion/3/arnes.jpg" },
    { label: "Casco", src: "imagenes/ventilacion/3/casco.jpg" },
    { label: "Guantes mecánicos", src: "imagenes/ventilacion/3/guantes.jpg" },
    { label: "Botas", src: "imagenes/ventilacion/3/botas.jpg" },
  ],
  "zonas-toxicas": [
    { label: "SCBA", src: "imagenes/ventilacion/4/scba.jpg" },
    { label: "Traje encapsulado", src: "imagenes/ventilacion/4/traje.jpg" },
    { label: "Guantes químicos", src: "imagenes/ventilacion/4/guantes.jpg" },
    { label: "Botas", src: "imagenes/ventilacion/4/bota.jpg" },
  ],
  "revisar-ventiladores": [
    { label: "Protección auditiva", src: "imagenes/ventilacion/5/auditiva.jpg" },
    { label: "Lentes", src: "imagenes/ventilacion/5/lentes.jpg" },
    { label: "Guantes", src: "imagenes/ventilacion/5/guantes.jpg" },
    { label: "Casco", src: "imagenes/ventilacion/5/casco.jpg" },
  ],
  "temperaturas-extremas": [
    { label: "Chaleco de enfriamiento / ropa térmica", src: "imagenes/ventilacion/6/chaleco.jpg" },
    { label: "Casco", src: "imagenes/ventilacion/6/casco.jpg" },
    { label: "Guantes", src: "imagenes/ventilacion/6/guantes.jpg" },
    { label: "Botas", src: "imagenes/ventilacion/6/botas.jpg" },
  ],
  "ajustar-flujo": [
    { label: "Casco", src: "imagenes/ventilacion/7/casco.jpg" },
    { label: "Guantes", src: "imagenes/ventilacion/7/guantes.jpg" },
    { label: "Botas", src: "imagenes/ventilacion/7/botas.jpg" },
    { label: "Lentes", src: "imagenes/ventilacion/7/lentes.jpg" },
  ],
  "inspeccionar-rutas": [
    { label: "Casco con lámpara minera", src: "imagenes/ventilacion/8/casco.jpg" },
    { label: "Botas", src: "imagenes/ventilacion/8/bota.jpg" },
    { label: "Guantes", src: "imagenes/ventilacion/8/guantes.jpg" },
    { label: "Detector (opcional)", src: "imagenes/ventilacion/8/detector.jpg" },
  ],

  // ===== ELECTRICISTA MINERO =====
  "reparar-tableros": [
    { label: "Traje contra arco eléctrico", src: "imagenes/electrico/1/traje.jpg" },
    { label: "Pantalla facial", src: "imagenes/electrico/1/casco.jpg" },
    { label: "Guantes dieléctricos", src: "imagenes/electrico/1/guantes.jpg" },
    { label: "Balaclava ignífuga", src: "imagenes/electrico/1/balaclva.jpg" },
  ],
  "instalar-cableado": [
    { label: "Casco dieléctrico", src: "imagenes/electrico/2/casco.jpg" },
    { label: "Botas dieléctricas", src: "imagenes/electrico/2/botas.jpg" },
    { label: "Herramientas aisladas", src: "imagenes/electrico/2/herramientas.jpg" },
    { label: "Lentes", src: "imagenes/electrico/2/lentes.jpg" },
  ],
  "probar-voltaje": [
    { label: "Guantes aislantes", src: "imagenes/electrico/3/guantes.jpg" },
    { label: "Detector de voltaje", src: "imagenes/electrico/3/detector.jpg" },
    { label: "Lentes", src: "imagenes/electrico/3/lentes.jpg" },
    { label: "Casco", src: "imagenes/electrico/3/casco.jpg" },
  ],
  "loto": [
    { label: "Kit LOTO", src: "imagenes/electrico/4/kit.jpg" },
    { label: "Guantes dieléctricos", src: "imagenes/electrico/4/guantes.jpg" },
    { label: "Casco", src: "imagenes/electrico/4/casco.jpg" },
    { label: "Candados / etiquetas", src: "imagenes/electrico/4/candado.jpg" },
  ],
  "humedad": [
    { label: "Botas dieléctricas", src: "imagenes/electrico/5/botas.jpg" },
    { label: "Tapete aislante", src: "imagenes/electrico/5/tapete.jpg" },
    { label: "Guantes dieléctricos", src: "imagenes/electrico/5/guantes.jpg" },
    { label: "Lentes", src: "imagenes/electrico/5/lentes.jpg" },
  ],
  "atender-fallas": [
    { label: "Ropa FR", src: "imagenes/electrico/6/ropa.jpg" },
    { label: "Pantalla facial", src: "imagenes/electrico/6/pantalla.jpg" },
    { label: "Guantes dieléctricos", src: "imagenes/electrico/6/guantes.jpg" },
    { label: "Casco dieléctrico", src: "imagenes/electrico/6/casco.jpg" },
  ],
  "energia-residual": [
    { label: "Detector de voltaje", src: "imagenes/electrico/7/detector.jpg" },
    { label: "Guantes aislantes", src: "imagenes/electrico/7/guantes.jpg" },
    { label: "Lentes", src: "imagenes/electrico/7/lentes.jpg" },
    { label: "Casco", src: "imagenes/electrico/7/casco.jpg" },
  ],
  "mantenimiento": [
    { label: "Guantes mecánicos", src: "imagenes/electrico/8/guantes.jpg" },
    { label: "Lentes", src: "imagenes/electrico/8/lentes.jpg" },
    { label: "Casco", src: "imagenes/electrico/8/casco.jpg" },
    { label: "Botas", src: "imagenes/electrico/8/botas.jpg" },
  ],

  // ===== OPERADOR OFF-ROAD =====
  "conducir-rampas": [
    { label: "Cinturón de seguridad", src: "imagenes/operadorCamion/1/cinturon.jpg" },
    { label: "Casco", src: "imagenes/operadorCamion/1/casco.jpg" },
    { label: "Botas antiderrapantes", src: "imagenes/operadorCamion/1/botas.jpg" },
    { label: "Chaleco reflejante", src: "imagenes/operadorCamion/1/chaleco.jpg" },
  ],
  "baja-visibilidad": [
    { label: "Ropa alta visibilidad", src: "imagenes/operadorCamion/2/ropa.jpg" },
    { label: "Lámpara", src: "imagenes/operadorCamion/2/lampara.jpg" },
    { label: "Lentes", src: "imagenes/operadorCamion/2/lentes.jpg" },
    { label: "Casco", src: "imagenes/operadorCamion/2/casco.jpg" },
  ],
  "cargar-material": [
    { label: "Casco", src: "imagenes/operadorCamion/3/casco.jpg" },
    { label: "Lentes de impacto", src: "imagenes/operadorCamion/3/lentes.jpg" },
    { label: "Botas", src: "imagenes/operadorCamion/3/botas.jpg" },
    { label: "Guantes", src: "imagenes/operadorCamion/3/guantes.jpg" },
  ],
  "revisar-frenos": [
    { label: "Guantes mecánicos", src: "imagenes/operadorCamion/4/guantes.jpg" },
    { label: "Lentes", src: "imagenes/operadorCamion/4/lentes.jpg" },
    { label: "Casco", src: "imagenes/operadorCamion/4/casco.jpg" },
    { label: "Botas", src: "imagenes/operadorCamion/4/botas.jpg" },
  ],
  "descargar-material": [
    { label: "Casco con barbiquejo", src: "imagenes/operadorCamion/5/casco.jpg" },
    { label: "Lentes", src: "imagenes/operadorCamion/5/lentes.jpg" },
    { label: "Botas", src: "imagenes/operadorCamion/5/botas.jpg" },
    { label: "Guantes", src: "imagenes/operadorCamion/5/guantes.jpg" },
  ],
  "revisar-neumaticos": [
    { label: "Botas metatarsales", src: "imagenes/operadorCamion/6/botas.jpg" },
    { label: "Guantes reforzados", src: "imagenes/operadorCamion/6/guantes.jpg" },
    { label: "Lentes", src: "imagenes/operadorCamion/6/lentes.jpg" },
    { label: "Casco", src: "imagenes/operadorCamion/6/casco.jpg" },
  ],
  "jornadas": [
    { label: "Soporte lumbar", src: "imagenes/operadorCamion/7/lumbar.jpg" },
    { label: "Asiento ergonómico", src: "imagenes/operadorCamion/7/asiento.jpg" },
    { label: "Hidratación (opcional)", src: "imagenes/operadorCamion/7/hidratacion.jpg" },
    { label: "Pausas activas (opcional)", src: "imagenes/operadorCamion/7/pausas.jpg" },
  ],
  "cargar-combustible": [
    { label: "Guantes químicos", src: "imagenes/operadorCamion/8/guantes.jpg" },
    { label: "Ropa antiestática", src: "imagenes/operadorCamion/8/ropa.jpg" },
    { label: "Lentes", src: "imagenes/operadorCamion/8/lentes.jpg" },
    { label: "Calzado adecuado", src: "imagenes/operadorCamion/8/botas.jpg" },
  ],
};

// Exponer global
window.EPP_IMAGENES_POR_ACTIVIDAD = EPP_IMAGENES_POR_ACTIVIDAD;

